CREATE USER 'USERNAME'@'localhost' IDENTIFIED WITH mysql_native_password;
GRANT USAGE ON *.* TO 'USERNAME'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
SET PASSWORD FOR 'USERNAME'@'localhost' = PASSWORD('USERNAME');
GRANT ALL PRIVILEGES ON `USERNAME\_%`.* TO 'USERNAME'@'localhost';
